version: '3'
services:
  cg-auth:
    container_name: cg-auth
    build: .
    ports:
      - '6443:6443'
    networks:
      - server-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.authportal.rule=Host(`auth.chrisgrime.com`)
      - traefik.http.routers.authportal.entrypoints=websecure
      - traefik.http.routers.authportal.tls.certresolver=myresolver
    volumes:
      - ~/cg-auth/:/app

networks:
  server-network:
    external: true